### ISSUE TITLE
mummerplot error message: "Inappropriate ioctl for device"

### ISSUE THREAD

**Issue by lfaller** [mummer4/mummer#36]
Hi all,

I am trying to run mummerplot on the command line to generate a png that shows how my two fasta sequences align. I am getting the following error message:

```
mummerplot -p atcc_vs_wt --png atcc_vs_wt.delta
gnuplot 4.6 patchlevel 6
Reading delta file atcc_vs_wt.delta
Writing plot files atcc_vs_wt.fplot, atcc_vs_wt.rplot
Writing gnuplot script atcc_vs_wt.gp
Rendering plot atcc_vs_wt.png
WARNING: Unable to run 'false atcc_vs_wt.gp', Inappropriate ioctl for device
```

*Some other information*

```
$ mummerplot --version
mummerplot 3.5

$ gnuplot --version
gnuplot 4.6 patchlevel 6
```

Any advice is appreciated!

**Comment by ljcohen** [comment]
I get the same error message as above:

```
[ljcohen@dev-intel14 mummer]$ mummerplot --fat --filter --png --large -p F_olivaceus F_oli_ONT_Fhet.delta
gnuplot 4.6 patchlevel 3
Writing filtered delta file F_olivaceus.filter
Reading delta file F_olivaceus.filter
Writing plot files F_olivaceus.fplot, F_olivaceus.rplot
Writing gnuplot script F_olivaceus.gp
Rendering plot F_olivaceus.png
WARNING: Unable to run 'false F_olivaceus.gp', Inappropriate ioctl for device
```

Version info:
```
[ljcohen@dev-intel14 mummer]$ mummerplot --version
mummerplot 3.5
[ljcohen@dev-intel14 mummer]$ gnuplot --version
gnuplot 4.6 patchlevel 3
``` 

Tried a previous version of gnuplot, same thing:
```
[ljcohen@dev-intel14 mummer]$ mummerplot --fat --filter --png --large -p F_olivaceus F_oli_ONT_Fhet.delta
gnuplot 4.4 patchlevel 4
Writing filtered delta file F_olivaceus.filter
Reading delta file F_olivaceus.filter
Writing plot files F_olivaceus.fplot, F_olivaceus.rplot
Writing gnuplot script F_olivaceus.gp
Rendering plot F_olivaceus.png
WARNING: Unable to run 'false F_olivaceus.gp', Inappropriate ioctl for device
```

Installed stable version of [gnuplot (5.2.0)](https://sourceforge.net/projects/gnuplot/files/):

```
cd ~/bin
wget wget https://downloads.sourceforge.net/project/gnuplot/gnuplot/5.2.0/gnuplot-5.2.0.tar.gz
tar -xvzf gnuplot-5.2.0.tar.gz
cd gnuplot-5.2.0
make install
cd src
./gnuplot --version # confirms the version installed
echo export PATH=$(pwd):$PATH >> ~/.bashrc
source ~/.bashrc
```

Same problem:
```
[ljcohen@dev-intel14 mummer]$ mummerplot --fat --filter --png --large -p F_olivaceus F_oli_ONT_Fhet.delta
gnuplot 5.2 patchlevel 0
Writing filtered delta file F_olivaceus.filter
Reading delta file F_olivaceus.filter
Writing plot files F_olivaceus.fplot, F_olivaceus.rplot
Writing gnuplot script F_olivaceus.gp
Rendering plot F_olivaceus.png
WARNING: Unable to run 'false F_olivaceus.gp', Inappropriate ioctl for device
```

This seems to be a recurring issue with `mummerplot`. Per a [suggestion on this forum page](https://sourceforge.net/p/mummer/mailman/message/34939032/), I was able to fix before by commenting out 3 lines of code that have the word 'mouse' (search for `clipboardformat`). But that didn't fix the problem this time. Would appreciate any advice.

**Comment by ljcohen** [comment]
Installing the [previous version of mummer](https://github.com/mummer4/mummer/releases/tag/v3.9.4alpha), `3.9.4alpha` worked!
```
[ljcohen@dev-intel14 mummer]$ mummerplot --fat --filter --png --large -p F_olivaceus F_oli_ONT_Fhet.delta
gnuplot 5.2 patchlevel 0
Writing filtered delta file F_olivaceus.filter
Reading delta file F_olivaceus.filter
Writing plot files F_olivaceus.fplot, F_olivaceus.rplot
Writing gnuplot script F_olivaceus.gp
Rendering plot F_olivaceus.png
```
Although, it does say that the `mummerplot` version is the same as before, which is odd:

```
[ljcohen@dev-intel14 mummer]$ mummerplot --version
mummerplot 3.5
```

**Comment by aprezvykh** [comment]
for me,it has been solved by installing gnuplot v. 4.6

**Comment by bionicadmin** [comment]
When I was troubleshooting this issue, I realized that gnuplot was actually what was failing, not so much mummer, the error was indicating that I was using the wrong terminal for this output but no matter whether I specified x11, postscript, or png I was still getting the same error. Turns out, if you installed this software out of a docker container it is failing because this software is still trying to find gnuplot in the docker container, which is causing it to fail.

**Comment by asdcid** [comment]
After a few hours test, I solved this issue. I think the people who got
```WARNING: Unable to run 'false out.gp', Inappropriate ioctl for device```
is that when they installed mummer, the gnuplot was NOT in the environment path. The solution is simply, change the line 27 in mummerplot
```
my $GNUPLOT_EXE = "false";
```
to
```
my $GNUPLOT_EXE = "gnuplot";
```
If your gnuplot is in your environment path, just set "gnuplot", if not, put the path there, like what "$LIB_DIR" and "$BIN_DIR" did.

The point why mummer 3x worked but not mummer 4x is that in mummer 3x, they did not have the "$GNUPLOT_EXE" variable, they directly used "gnuplot". But in mummer 4x, they use "$GNUPLOT_EXE" to try to hardcode the path of gnuplot (I guess).

**Comment by ngrafgr** [comment]
Installing gnuplot(v5.2) like so worked for me
```
brew install gnuplot --with-x11
```

**Comment by zoumingr** [comment]
Actually it's the problem of gnuplot, whereas it's the problem of libgd.
when installing gnuplot, you can check the config.log,such as gnuplot-4.4.0/config.log and search png and it may be as follows:
configure:12420: result:   jpeg terminal: no (requires libgd with jpeg support)
configure:12433: result:   gif terminal: no (requires libgd with gif support)
configure:12442: result:   png terminal: no (requires libgd with png support)
configure:12450: result:     (jpeg, gif and png terminals cannot use TTF fonts, requires libgd support)
configure:12466: result:   pdf terminal: no (requires libpdf)
this means that the libgd is not installed and you can download and install it.
however, in some systems, it may encounter problems when you make it, you can test it as follows:
gcc -lgd --verbose
and you can fix it using 
export LD_LIBRARY_PATH="/som/place/to/libgd-2.2.5/lib:$LD_LIBRARY_PATH"
and if it don't work, just use
export LIBRARY_PATH="/som/place/to/libgd-2.2.5/lib:$LIBRARY_PATH"

**Comment by Frozoto1** [comment]
I use mummer v4.x and have not this error, you can try it.

**Comment by gexijin** [comment]
I also had this error. 
I followed asdcid's instruction above. The "false xxx.gp" clearly should be "gnplot xxx.gp". 
It took me a whole day to solve this. Another thing to realize is the mummer4 only works with gnuplot 4.6, NOT 5.0 or higher. 
Here is what I did from the beginning:

1.  Install Anaconda3 
sudo wget https://repo.anaconda.com/archive/Anaconda3-2019.07-Linux-x86_64.sh
Anaconda3-2019.07-Linux-x86_64.sh
conda init   
source ~/.bashrc
conda config --add channels bioconda    # add channel
unset PYTHONPATH    # this solve an error:  AttributeError: module 'enum' has no attribute 'IntFlag'

2.  Install Gnuplot 4.6,    I had error with the most recent version of gnuplot
 sudo  conda install -c bioconda gnuplot=4.6.0

3.  Install mummer4
sudo ./conda install -c bioconda mummer4

4. Solve an error:  "Can't find PostScript prologue file prologue.ps"

export GNUPLOT_PS_DIR=/home/YOURNAME/anaconda3/share/gnuplot/4.6/

**Comment by sunnycqcn** [comment]
gnuplot need set term with png. If you can not find term with png in your gnuplot, you have to install libgd or more packages. It is up to your system, for example graph-tools.

**Comment by girum89** [comment]
I had this problem****
gnuplot 5.2 patchlevel 2
Reading mummer file mummer.mums (use mummer -c)
Writing plot files mummer.fplot, mummer.rplot
Writing gnuplot script mummer.gp
Rendering plot mummer.ps

set mouse clipboardformat "[%.0f, %.0f]"
          ^
"mummer.gp", line 18: wrong option

WARNING: Unable to run 'gnuplot mummer.gp', Inappropriate ioctl for device
********************************

Problem gone after removing the "$P_FORMAT .= "\nset mouse clipboardformat \"$MFORMAT\"";" in line 1154 of mummerplot

**Comment by Superman-joshi** [comment]
I had the similar problem
I realized that i had installed gnuplot (using sudo apt-get install gnuplot)  after mummer installation.
So i uninstalled mummer and re-installed it. and it worked perfectly for me

**Comment by gonzalezibeas** [comment]
In my case commenting out the single line of the code mentioned by girum89 was not enough. I had to comment out the 3 lines of "$P_FORMAT" (lines 1153, 1154, 1155 of mummerplot file). In the last version of mummer the problem persists:

mummer, 4.0.0rc1
GnuPlot, gnuplot 5.2 patchlevel 8

**Comment by aersoares81** [comment]
I tried commenting on all these lines and it still won't work.

mummer 4.0.0rc1
gnuplot 5.0 patchlevel 3

**Comment by wshuai294** [comment]
Using mummer3 instead of mummer4 works for me.

**Comment by wook2014** [comment]
This problem seemed to be caused by deletion of function "set mouse clipboard" in gnuplot 5

**Comment by lsoldini** [comment]
I had similar issues with mummer/4.0.0rc1 and gnuplot/5.2.8. 

I tried many things and, finally, what worked was:

1) Use mummer4 for whatever purposes to create .delta file (I needed mummer4 specifically, but one could already use mummer3 here)

2) Use gnuplot/4.6 and mummer/3.23

3) This gave me the same error as [gexijin](https://github.com/gexijin) with  "Can't find PostScript prologue file prologue.ps" and this was resolved as suggested

**Comment by andres333medel** [comment]
Hi, I had the trouble with:
`WARNING: Unable to run 'false out.gp', Inappropriate ioctl for device`

I tried solving it in different ways (as mentioned in some comments here), but it did not work for me. I removed MUMer and gnuplot installed before and started again with this:

Installing the following tools to visualize:

```
conda install -c conda-forge fig2dev
conda install -c conda-forge xfig
conda install -c conda-forge gnuplot
sudo apt install build-essential
```

After this I installed MUMer4, but it showed me the same WARNING message. So I uninstalled the MUMer4 and installer the MUMer3 with:
`conda install -c bioconda mummer`

I hope it works for you.

**Comment by lalibelulalo** [comment]
> I had the similar problem I realized that i had installed gnuplot (using sudo apt-get install gnuplot) after mummer installation. So i uninstalled mummer and re-installed it. and it worked perfectly for me

It worked for me!

**Comment by nikhita-damaraju** [comment]
I followed all the steps above. Definitely check for `my $GNUPLOT_EXE = "gnuplot";` as mentioned above. For me, removing "= X11" as the default terminal set in the line `$OPT_terminal  = X11;  # -t option` worked.

**Comment by scintilla9** [comment]
Install the dependencies first:
`conda install -c conda-forge fig2dev xfig gnuplot -y`
Then install mummer4 from bioconda:
`conda install -c bioconda mummer4`
Finally, editing the mummerplot script as suggested above, form `my $GNUPLOT_EXE = "false"` to `my $GNUPLOT_EXE = "gnuplot"`

These works for me.

**Comment by johnstonmj** [comment]
Perhaps not the most elegant workaround:
I ran all the mummer4 commands in one environment except for mummerplot.
I created a second environment with mummer3 to call mummerplot (on the mummer4-generated delta file), and I managed to generate plots without any issues from gnuplot.
Just another alternative!

**Comment by splaisan** [comment]
[like]  Stéphane Plaisance reacted to your message:
________________________________
