### ISSUE TITLE
compiling error in procmaxmat.c

### ISSUE THREAD

**Issue by phpeters** [mummer4/mummer#16]
Hej, 

Thanks for providing a multit-hreaded version of mummer! 

However, I experienced a compiling error in procmaxmat.c. I compiled it with gcc4.9. Do you mind to have a look at this error?

Thanks a lot and best regards!
Philipp

....
gcc4.9 -O3 -I../libbasedir -I../streesrc   -c -o findmumcand.o findmumcand.c
findmumcand.c: In function ‘findmumcandidates’:
findmumcand.c:158:8: warning: assignment makes pointer from integer without a cast
   lptr = scanprefixfromnodestree (stree, &loc, ROOT (stree), 
        ^
findmumcand.c:175:12: warning: assignment makes pointer from integer without a cast
       lptr = scanprefixfromnodestree (stree, &loc, ROOT (stree), 
            ^
findmumcand.c:181:12: warning: assignment makes pointer from integer without a cast
       lptr = scanprefixstree (stree, &loc, &loc, lptr, right, 0);
            ^
gcc4.9 -O3 -I../libbasedir -I../streesrc   -c -o findmaxmat.o findmaxmat.c
gcc4.9 -O3 -I../libbasedir -I../streesrc   -c -o procmaxmat.o procmaxmat.c
procmaxmat.c:41:3: error: unknown type name ‘ArrayMUMcandidate’
   ArrayMUMcandidate mumcandtab;// a table containing MUM-candidates
   ^
procmaxmat.c: In function ‘storeMUMcandidate’:
procmaxmat.c:361:3: error: unknown type name ‘MUMcandidate’
   MUMcandidate *mumcandptr;
   ^
In file included from ../streesrc/streetyp.h:13:0,
                 from ../streesrc/streedef.h:13,
                 from procmaxmat.c:20:
../libbasedir/arraydef.h:63:15: error: request for member ‘nextfreeMUMcandidate’ in something not a structure or union
         if((A)->nextfree##TYPE >= (A)->allocated##TYPE)\
               ^
../libbasedir/arraydef.h:98:9: note: in expansion of macro ‘CHECKARRAYSPACE’
         CHECKARRAYSPACE(A,TYPE,L);\
         ^
.... [more of these errors] ....

../libbasedir/spacedef.h:83:11: note: in definition of macro ‘FREESPACE’
           P = NULL;\
           ^
procmaxmat.c:573:5: note: in expansion of macro ‘FREEARRAY’
     FREEARRAY(&matchprocessinfo.mumcandtab,MUMcandidate);
     ^
make[2]: *** [procmaxmat.o] Error 1
make[2]: Leaving directory `/software/MUMmer4/MUMmer4/src/kurtz/mm3src'
make[1]: *** [mummer] Error 2
make[1]: Leaving directory `/software/MUMmer4/MUMmer4/src/kurtz'
make: *** [kurtz] Error 2

**Comment by gmarcais** [comment]
I can't reproduce that error on my ubuntu machine with gcc 4.9. Can you give me more details about your setup? OS version?

**Comment by phpeters** [comment]
Thanks for the quick reply!

I could "fix" it myself by downloading the mummer-4.0.0beta.tar.gz, instead of the master.zip (from the "clone and download" button).

I'm working on a CentOS 6.7 with a hand-installed (so, doing "make CC=gcc4.9 CXX=g++4.9"). swig is installed, too. Perhaps it was this yaggo?

Anyway, it works fine! Thanks for caring!

**Comment by gmarcais** [comment]
Glad it worked.
